---
services:
  postfix:
    image: postfixdocker
    build:
      context: .
      dockerfile: Dockerfile
    env_file: env
    networks:
      - mail
    volumes:
      - postfix-vol-1:/var/spool/postfix
networks:
  mail:
    name: mail